//go:build linux && amd64

package restic

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"testing"
	"time"
)

// Explicit opt-in: real system restic, exclusively generated private temporary
// repository/source/destination. No VM, supplied image, device or mount access.
func TestResticGeneratedRepository(t *testing.T) {
	if os.Getenv("VIRMILL_TEST_RESTIC") != "1" {
		t.Skip("set VIRMILL_TEST_RESTIC=1 only for generated-file system-restic qualification")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	tool := Tool{}
	identity, err := tool.Identity(ctx)
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("restic identity: %+v", identity)
	r, source := fixture(t)
	r.Path = filepath.Join(filepath.Dir(r.Path), "native-new-repository")
	if err = tool.Init(ctx, r); err != nil {
		t.Fatal(err)
	}
	snapshot, err := tool.Backup(ctx, r, source, testOperation)
	if err != nil {
		t.Fatal(err)
	}
	observed, err := tool.Observe(ctx, r, testOperation)
	if err != nil || len(observed) != 1 || !reflect.DeepEqual(observed[0], snapshot) {
		t.Fatal("operation snapshot mismatch", observed, err)
	}
	if _, err = tool.Backup(ctx, r, source, testOperation); err == nil {
		t.Fatal("existing operation replayed")
	}
	if err = tool.Check(ctx, r); err != nil {
		t.Fatal(err)
	}
	destination := filepath.Join(filepath.Dir(r.Path), "native-new-restore")
	if err = tool.Restore(ctx, r, snapshot.ID, destination); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(destination, 0700) })
	// Relative backup restores member metadata; the new extraction root stays
	// 0700. The coordinator verifies and seals that root separately.
	for path, mode := range map[string]os.FileMode{destination: 0700, filepath.Join(destination, "member"): 0400} {
		st, err := os.Stat(path)
		if err != nil || st.Mode().Perm() != mode {
			t.Fatalf("restored private mode differs for %s: %v %v", path, st, err)
		}
	}
	for _, path := range []string{filepath.Join(source, "member"), filepath.Join(destination, "member")} {
		b, err := os.ReadFile(path)
		if err != nil || string(b) != "generated captured member" {
			t.Fatal("exact generated bytes not retained/restored", path, err)
		}
	}
	if err = tool.Restore(ctx, r, snapshot.ID, destination); err == nil {
		t.Fatal("existing restore destination reused")
	}
}
