//go:build linux && cgo

package libvirt

import (
	"encoding/xml"
	"virmill.local/core/internal/domain"
)

const creationGuestAgentDevices = `<controller type="virtio-serial" index="0" model="virtio"/><channel type="unix"><target type="virtio" name="org.qemu.guest_agent.0"/><address type="virtio-serial" controller="0" bus="0" port="1"/></channel>`

// normalizeCreationGuestAgent applies only to an explicitly requested new-VM
// channel. Its source is deliberately omitted: libvirt owns socket allocation.
// Persistent XML must keep that automatic policy rather than substitute a path.
// https://libvirt.org/formatdomain.html#channel
// The documented inactive normalization removes an autogenerated source path;
// a source element here cannot prove that its path belongs to libvirt, so fails.
func normalizeCreationGuestAgent(w, g *xmlNode) error {
	wd, gd := child(w, "devices"), child(g, "devices")
	if wd == nil || gd == nil {
		return nil
	} // The general matcher reports missing devices.
	requested := false
	for _, n := range wd.children {
		if n.name == (xml.Name{Local: "channel"}) {
			requested = true
		}
	}
	if !requested {
		return nil
	} // Preserve existing receipt semantics exactly.
	fail := func() error {
		return domain.Fail("RECOVERY_REQUIRED", "guest-agent channel or controller differs from the reviewed automatic socket policy")
	}
	validate := func(devices *xmlNode, observed bool) error {
		channels, controllers := 0, 0
		for _, n := range devices.children {
			switch {
			case n.name.Local == "channel":
				channels++
				if !onlyAttrs(n, []string{"type"}, nil) || attr(n, "type") != "unix" {
					return fail()
				}
				seen := map[string]bool{}
				kept := []*xmlNode{}
				for _, c := range n.children {
					if c.name.Space != "" || seen[c.name.Local] {
						return fail()
					}
					seen[c.name.Local] = true
					switch c.name.Local {
					case "target":
						if !onlyAttrs(c, []string{"type", "name"}, nil) || len(c.children) != 0 || attr(c, "type") != "virtio" || attr(c, "name") != "org.qemu.guest_agent.0" {
							return fail()
						}
					case "address":
						if !onlyAttrs(c, []string{"type", "controller", "bus", "port"}, nil) || len(c.children) != 0 || attr(c, "type") != "virtio-serial" || attr(c, "controller") != "0" || attr(c, "bus") != "0" || attr(c, "port") != "1" {
							return fail()
						}
					case "alias":
						if !observed || !onlyAttrs(c, []string{"name"}, nil) || len(c.children) != 0 || attr(c, "name") != "channel0" {
							return fail()
						}
						continue
					default:
						return fail() // Includes source, reconnect, seclabel and protocol.
					}
					kept = append(kept, c)
				}
				if !seen["target"] || !seen["address"] {
					return fail()
				}
				n.children = kept
			case n.name.Local == "controller" && attr(n, "type") == "virtio-serial":
				controllers++
				if !onlyAttrs(n, []string{"type", "index", "model"}, nil) || attr(n, "index") != "0" || attr(n, "model") != "virtio" {
					return fail()
				}
				seen := map[string]bool{}
				for _, c := range n.children {
					if c.name.Space != "" || seen[c.name.Local] {
						return fail()
					}
					seen[c.name.Local] = true
					switch c.name.Local {
					case "alias":
						if !observed || !onlyAttrs(c, []string{"name"}, nil) || len(c.children) != 0 || attr(c, "name") != "virtio-serial0" {
							return fail()
						}
					case "address":
						if !observed {
							return fail()
						}
						if _, ok := parseCreationPCI(c); !ok {
							return fail()
						}
					default:
						return fail()
					}
				}
			}
		}
		if channels != 1 || controllers != 1 {
			return fail()
		}
		return nil
	}
	if err := validate(wd, false); err != nil {
		return err
	}
	return validate(gd, true)
}
