//go:build linux && amd64

package creating

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"strings"
	"testing"

	"virmill.local/core/internal/app"
	"virmill.local/core/internal/backend/seed"
	"virmill.local/core/internal/domain"
	"virmill.local/core/internal/operations"
	"virmill.local/core/internal/wire"
)

func estimateRecipe(t *testing.T, s *Service, p domain.Plan) (input, []byte) {
	t.Helper()
	_, encoded, err := s.Store.Plan(p.ID)
	if err != nil {
		t.Fatal(err)
	}
	var in input
	if err := wire.Decode(encoded, &in); err != nil {
		t.Fatal(err)
	}
	return in, encoded
}

func assertEstimateDidNotMutate(t *testing.T, backend *fixtureBackend) {
	t.Helper()
	if backend.allocated != 0 || backend.populated != 0 || backend.definitions != 0 || backend.defined || len(backend.volumes) != 0 || len(backend.verified) != 0 {
		t.Fatal("space estimate caused a provider mutation")
	}
}

func TestCreationPlansPublishPoolBudgetDistinctFromCopiedPayload(t *testing.T) {
	for _, mode := range []string{"ordinary", "installation-media", "provisioned"} {
		t.Run(mode, func(t *testing.T) {
			var s *Service
			var backend *fixtureBackend
			var request app.Request
			tool := &seedPhaseTool{}
			switch mode {
			case "ordinary":
				s, backend, request, _ = creationFixture(t)
			case "installation-media":
				s, backend, request = creationMediaFixture(t)
			case "provisioned":
				s, backend, request = provisioningFixture(t, tool)
			}
			p, err := s.Plan(context.Background(), 1000, request)
			if err != nil {
				t.Fatal(err)
			}
			in, encoded := estimateRecipe(t, s, p)
			// Two tiny prepared disks need a 64 MiB reserve, 16 MiB headroom each and
			// their own sizes; their 1 MiB virtual size no longer counts (ADR 0060).
			want := uint64(64<<20+2*(16<<20)) + 78
			if in.SpaceBudget != spaceBudgetFileBytes || in.HandOver != nil {
				t.Fatalf("new plans use the file-size budget and keep the prepared copy: %q %+v", in.SpaceBudget, in.HandOver)
			}
			if mode != "ordinary" {
				want += 40 * 2048
			}
			if p.Estimates.AdditionalBytes != want || p.Review["requiredFreeBytes"] != want || in.RequiredBytes != want || p.Estimates.RequiresDowntime {
				t.Fatalf("plan/review/recipe accounting differs: estimates=%+v review=%v recipe=%d want=%d", p.Estimates, p.Review["requiredFreeBytes"], in.RequiredBytes, want)
			}
			var copied uint64
			for _, v := range in.Volumes {
				copied += v.FileBytes
			}
			if copied >= want || !strings.Contains(p.Estimates.Notes, fmt.Sprintf("Copied volume payload: %d bytes", copied)) || !strings.Contains(p.Estimates.Notes, "Initial physical allocation") || !strings.Contains(p.Estimates.Notes, "elapsed time is not estimated") {
				t.Fatalf("estimate conflates space quantities: %+v copied=%d", p.Estimates, copied)
			}
			cacheNote := fmt.Sprintf("%d-byte free-space budget at the private seed-cache", seed.MaxISOBytes+3*seed.MaxContentBytes+(1<<20))
			if strings.Contains(p.Estimates.Notes, cacheNote) != (mode == "provisioned") || mode == "provisioned" && tool.calls.Load() != 1 {
				t.Fatal("seed cache omitted, double-counted or regenerated by estimate", p.Estimates)
			}
			// Estimate is pure even with no backend, inventory, source loader or store.
			again, err := (&Service{}).Estimate(context.Background(), p, encoded)
			if err != nil || again != p.Estimates {
				t.Fatalf("unstable or provider-dependent estimate: %v", err)
			}
			stored, _, err := s.Store.Plan(p.ID)
			if err != nil || stored.Estimates != p.Estimates || stored.Digest != p.Digest {
				t.Fatal("estimates were not persisted with the reviewed plan", err)
			}
			changed := p
			changed.Estimates.AdditionalBytes++
			digest, err := operations.PlanDigest(changed)
			if err != nil || digest == p.Digest {
				t.Fatal("space estimate is outside plan authorization digest", err)
			}
			assertEstimateDidNotMutate(t, backend)
		})
	}
}

func TestCreationEstimateSupportsBothRecipeVersions(t *testing.T) {
	s, backend, request, _ := creationFixture(t)
	current, err := s.Plan(context.Background(), 1000, request)
	if err != nil {
		t.Fatal(err)
	}
	in, _ := estimateRecipe(t, s, current)
	in.Target.Spec.DevicePolicy = nil
	legacy, err := s.Engine.Plan(context.Background(), 1000, current.ConnectionID, "vm.create", append([]string{}, current.ResourceIDs...), current.Before, in, []domain.Step{{ID: "create", Action: "vm.create"}}, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	if legacy.Estimates != current.Estimates || legacy.Review["requiredFreeBytes"] != current.Review["requiredFreeBytes"] {
		t.Fatal("legacy and devices-v1 space accounting diverged")
	}
	for _, operation := range []string{"vm.create", "vm.create.devices-v1"} {
		if _, ok := s.Engine.Handlers[operation].(operations.PlanEstimator); !ok {
			t.Fatalf("%s handler has no estimator", operation)
		}
	}
	assertEstimateDidNotMutate(t, backend)
}

func TestCreationEstimateNativeReportedBudgetRegression(t *testing.T) {
	s, _, request, _ := creationFixture(t)
	p, err := s.Plan(context.Background(), 1000, request)
	if err != nil {
		t.Fatal(err)
	}
	in, _ := estimateRecipe(t, s, p)
	in.Target.Spec.Disks, in.Artifact.Disks, in.Volumes = in.Target.Spec.Disks[:1], in.Artifact.Disks[:1], in.Volumes[:1]
	in.Artifact.Disks[0].VirtualBytes = 32 << 20
	in.Volumes[0].VirtualBytes = 32 << 20
	// Recipes written before ADR 0060 keep the virtual-size budget.
	in.SpaceBudget = ""
	in.RequiredBytes = 125829120
	encoded, err := operations.Canonical(in)
	if err != nil {
		t.Fatal(err)
	}
	estimate, err := (&Service{}).Estimate(context.Background(), p, encoded)
	if err != nil || estimate.AdditionalBytes != 125829120 {
		t.Fatalf("32 MiB disk again reports zero pool headroom: %+v %v", estimate, err)
	}
}

func TestCreationEstimateRejectsInvalidPersistedAccounting(t *testing.T) {
	s, backend, request := provisioningFixture(t, &seedPhaseTool{})
	p, err := s.Plan(context.Background(), 1000, request)
	if err != nil {
		t.Fatal(err)
	}
	_, base := estimateRecipe(t, s, p)
	for name, mutate := range map[string]func(*input){
		"zero required budget":          func(in *input) { in.RequiredBytes = 0 },
		"inflated required budget":      func(in *input) { in.RequiredBytes++ },
		"missing volumes":               func(in *input) { in.Volumes = nil },
		"extra volume":                  func(in *input) { in.Volumes = append(in.Volumes, in.Volumes[0]) },
		"missing source disk":           func(in *input) { in.Artifact.Disks = in.Artifact.Disks[1:] },
		"duplicate source disk":         func(in *input) { in.Artifact.Disks[1] = in.Artifact.Disks[0] },
		"duplicate disk mapping":        func(in *input) { in.Target.Spec.Disks[1] = in.Target.Spec.Disks[0] },
		"reordered volume mapping":      func(in *input) { in.Volumes[0], in.Volumes[1] = in.Volumes[1], in.Volumes[0] },
		"missing pool identity":         func(in *input) { in.Target.Spec.PoolID = "" },
		"different volume pool":         func(in *input) { in.Volumes[0].PoolID = "other" },
		"duplicate volume name":         func(in *input) { in.Volumes[1].Name = in.Volumes[0].Name },
		"negative source virtual bytes": func(in *input) { in.Artifact.Disks[0].VirtualBytes = -1; in.Volumes[0].VirtualBytes = ^uint64(0) },
		"negative source file bytes":    func(in *input) { in.Artifact.Disks[0].FileBytes = -1; in.Volumes[0].FileBytes = ^uint64(0) },
		"zero virtual bytes":            func(in *input) { in.Artifact.Disks[0].VirtualBytes = 0; in.Volumes[0].VirtualBytes = 0 },
		"zero copied bytes":             func(in *input) { in.Artifact.Disks[0].FileBytes = 0; in.Volumes[0].FileBytes = 0 },
		"oversized disk": func(in *input) {
			in.Artifact.Disks[0].VirtualBytes = (512 << 30) + 1
			in.Volumes[0].VirtualBytes = uint64(in.Artifact.Disks[0].VirtualBytes)
		},
		"overflowed disk intent":            func(in *input) { in.Volumes[0].VirtualBytes = ^uint64(0) },
		"overflowed copied intent":          func(in *input) { in.Volumes[0].FileBytes = ^uint64(0) },
		"copied bytes exceed disk headroom": func(in *input) { in.Artifact.Disks[0].FileBytes = 32 << 20; in.Volumes[0].FileBytes = 32 << 20 },
		"volume source mismatch":            func(in *input) { in.Volumes[0].SourceID = "other" },
		"virtual size mismatch":             func(in *input) { in.Volumes[0].VirtualBytes++ },
		"file size mismatch":                func(in *input) { in.Volumes[0].FileBytes++ },
		"digest binding mismatch":           func(in *input) { in.Volumes[0].SHA256 = strings.Repeat("f", 64) },
		"unexpected disk content type":      func(in *input) { in.Volumes[0].ContentType = "cdrom-iso" },
		"wrong media content type":          func(in *input) { in.Volumes[2].ContentType = "" },
		"media size mismatch":               func(in *input) { in.Volumes[2].VirtualBytes++ },
		"seed omitted":                      func(in *input) { in.Seed = nil },
		"seed source collision":             func(in *input) { in.Seed.Config.MediaID = in.Target.Spec.Disks[0].SourceID },
		"seed zero bytes":                   func(in *input) { in.Seed.Artifact.FileBytes = 0 },
		"seed negative bytes":               func(in *input) { in.Seed.Artifact.FileBytes = -1 },
		"seed excessive bytes":              func(in *input) { in.Seed.Artifact.FileBytes = seed.MaxISOBytes + 2048 },
		"seed nonsector bytes":              func(in *input) { in.Seed.Artifact.FileBytes++ },
		"device policy version mismatch":    func(in *input) { in.Target.Spec.DevicePolicy = nil },
	} {
		t.Run(name, func(t *testing.T) {
			var in input
			if err := wire.Decode(base, &in); err != nil {
				t.Fatal(err)
			}
			mutate(&in)
			encoded, err := operations.Canonical(in)
			if err != nil {
				t.Fatal(err)
			}
			got, err := (&Service{}).Estimate(context.Background(), p, encoded)
			if err == nil || got != (domain.Estimates{}) {
				t.Fatalf("invalid accounting returned estimate: %+v %v", got, err)
			}
		})
	}
	for name, encoded := range map[string][]byte{
		"malformed": []byte("{"),
		"unknown":   bytes.Replace(base, []byte(`"requiredBytes":`), []byte(`"unknown":true,"requiredBytes":`), 1),
		"duplicate": bytes.Replace(base, []byte(`"requiredBytes":`), []byte(`"requiredBytes":0,"requiredBytes":`), 1),
	} {
		t.Run(name, func(t *testing.T) {
			got, err := (&Service{}).Estimate(context.Background(), p, encoded)
			if err == nil || got != (domain.Estimates{}) {
				t.Fatal("malformed recipe returned estimate")
			}
		})
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if got, err := (&Service{}).Estimate(ctx, p, base); !errors.Is(err, context.Canceled) || got != (domain.Estimates{}) {
		t.Fatal("canceled estimate returned success", got, err)
	}
	p.Operation = "vm.create.resume"
	if got, err := (&Service{}).Estimate(context.Background(), p, base); err == nil || got != (domain.Estimates{}) {
		t.Fatal("another operation accepted creation estimate")
	}
	assertEstimateDidNotMutate(t, backend)
}

func TestCreationEstimateFailurePreventsPlanPersistence(t *testing.T) {
	s, backend, request, _ := creationFixture(t)
	p, err := s.Plan(context.Background(), 1000, request)
	if err != nil {
		t.Fatal(err)
	}
	in, _ := estimateRecipe(t, s, p)
	in.RequiredBytes = 0 // Passes the old read-only space comparison; estimator must refuse it.
	var before int
	if err := s.Store.DB.QueryRow("SELECT count(*) FROM plans").Scan(&before); err != nil {
		t.Fatal(err)
	}
	_, err = s.Engine.Plan(context.Background(), 1000, p.ConnectionID, p.Operation, append([]string{}, p.ResourceIDs...), p.Before, in, p.Steps, p.Acknowledgements, p.Risks)
	if err == nil {
		t.Fatal("contradictory estimate persisted")
	}
	var after, jobs int
	if err := s.Store.DB.QueryRow("SELECT count(*) FROM plans").Scan(&after); err != nil {
		t.Fatal(err)
	}
	if err := s.Store.DB.QueryRow("SELECT count(*) FROM jobs").Scan(&jobs); err != nil {
		t.Fatal(err)
	}
	if before != after || jobs != 0 {
		t.Fatal("invalid estimate created a plan or job", before, after, jobs)
	}
	assertEstimateDidNotMutate(t, backend)
}

func TestCreationSpaceArithmeticCannotWrap(t *testing.T) {
	max := ^uint64(0)
	if sum, ok := creationAddBytes(max-1, 1); !ok || sum != max {
		t.Fatal("exact unsigned sum boundary refused")
	}
	if sum, ok := creationAddBytes(max, 1); ok || sum != 0 {
		t.Fatal("unsigned sum wrapped into a successful estimate")
	}
	if budget, ok := creationDiskBudget(max); ok || budget != 0 {
		t.Fatal("disk headroom arithmetic wrapped")
	}
	if budget, ok := creationDiskBudget(512 << 30); !ok || budget != 687211544576 {
		t.Fatal("maximum supported virtual disk budget differs", budget, ok)
	}
	if budget, ok := creationDiskBudget(5); !ok || budget != (16<<20)+6 {
		t.Fatal("25 percent integer-floor policy changed", budget, ok)
	}
}

var _ operations.PlanEstimator = (*Service)(nil)
