#!/usr/bin/env python3
"""Render the requirements matrix; --check detects drift, --release fails closed."""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
original = json.loads((ROOT / 'virmill-v1-spec/contracts/requirements.json').read_text())
tracker = json.loads((ROOT / 'docs/evidence/requirements.json').read_text())
assert len(tracker['requirements']) == 71
assert {r['id'] for r in tracker['requirements']} == {r['id'] for r in original['requirements']}
for a, b in zip(original['requirements'], tracker['requirements']):
    for key in ('id', 'acceptance', 'minimumEvidence', 'v1Required'):
        assert a[key] == b[key], (a['id'], key)
lines = ['# Implementation and release traceability', '',
         'Generated by `python3 scripts/traceability.py`. All 71 scenarios remain mandatory.',
         'Status distinguishes code progress from the required release evidence; no configuration is certified.', '',
         '| ID | Gate / owner | Implementation status | Paths / executed tests | Required evidence | Outstanding |',
         '|---|---|---|---|---|---|']
for r in tracker['requirements']:
    paths = ', '.join(r['implementationPaths'] + r['tests']) or 'Planned: ' + r['plannedTest']
    lines.append(f"| {r['id']} | {r['gate']} / {r['owner']} | {r['status']} | {paths} | {r['minimumEvidence']} | {'; '.join(r['outstanding'])} |")
text = '\n'.join(lines) + '\n'
target = ROOT / 'docs/implementation-status.md'
if '--check' in sys.argv:
    assert target.read_text() == text, 'Run scripts/traceability.py'
else:
    target.write_text(text)
ledger = [json.loads(s) for s in (ROOT / 'docs/evidence/ledger.jsonl').read_text().splitlines()]
evidence_lines = ['# Requirements to recorded evidence', '',
    'Generated by `python3 scripts/traceability.py` from the 71-row tracker and append-only ledger.',
    'A passing scoped test is not acceptance of a hardware or complete-workflow requirement.',
    'Each ledger entry records its own revision, source digest, fixture hashes and limitations.', '',
    '| Requirement | Recorded checks (result / class) | Required qualification | Status |',
    '|---|---|---|---|']
for r in tracker['requirements']:
    related = [e for e in ledger if r['id'] in e.get('requirements', []) or e['id'] in r['evidence']]
    checks = '; '.join(f"[{e['id']}](evidence/{e['log']}) ({e['result']} / {e['evidenceClass']})" for e in related) or 'None recorded'
    accepted = 'accepted' if r['status'] == 'accepted' else 'not accepted'
    evidence_lines.append(f"| {r['id']} | {checks} | {r['minimumEvidence']} | {r['status']}; {accepted} |")
evidence_text = '\n'.join(evidence_lines) + '\n'
evidence_target = ROOT / 'docs/requirements-to-evidence.md'
if '--check' in sys.argv:
    assert evidence_target.read_text() == evidence_text, 'Run scripts/traceability.py to update evidence matrix'
else:
    evidence_target.write_text(evidence_text)
if '--release' in sys.argv:
    if '- [ ]' in (ROOT / 'SHIP-CHECKLIST.md').read_text():
        print('Complete release checklist contains unchecked requirements.')
    blocked = [r['id'] for r in tracker['requirements'] if r['status'] != 'accepted' or not r['evidence'] or r['outstanding']]
    if '- [ ]' in (ROOT / 'SHIP-CHECKLIST.md').read_text():
        blocked.append('SHIP-CHECKLIST')
    if blocked:
        sys.exit('Release blocked: ' + ', '.join(blocked))
print('71 acceptance records validated; matrix consistent.')
