#!/usr/bin/env python3
"""Render the requirements matrix; --check detects drift, --release fails closed."""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
original = json.loads((ROOT / 'virmill-v1-spec/contracts/requirements.json').read_text())
tracker = json.loads((ROOT / 'docs/evidence/requirements.json').read_text())
assert len(tracker['requirements']) == 71
assert {r['id'] for r in tracker['requirements']} == {r['id'] for r in original['requirements']}
for a, b in zip(original['requirements'], tracker['requirements']):
    for key in ('id', 'acceptance', 'minimumEvidence', 'v1Required'):
        assert a[key] == b[key], (a['id'], key)
lines = ['# Implementation and release traceability', '',
         'Generated by `python3 scripts/traceability.py`. All 71 scenarios remain mandatory.',
         'Status distinguishes code progress from the required release evidence; no configuration is certified.', '',
         '| ID | Gate / owner | Implementation status | Paths / executed tests | Required evidence | Outstanding |',
         '|---|---|---|---|---|---|']
for r in tracker['requirements']:
    paths = ', '.join(r['implementationPaths'] + r['tests']) or 'Planned: ' + r['plannedTest']
    lines.append(f"| {r['id']} | {r['gate']} / {r['owner']} | {r['status']} | {paths} | {r['minimumEvidence']} | {'; '.join(r['outstanding'])} |")
text = '\n'.join(lines) + '\n'
target = ROOT / 'docs/implementation-status.md'
if '--check' in sys.argv:
    assert target.read_text() == text, 'Run scripts/traceability.py'
else:
    target.write_text(text)
if '--release' in sys.argv:
    if '- [ ]' in (ROOT / 'SHIP-CHECKLIST.md').read_text():
        print('Complete release checklist contains unchecked requirements.')
    blocked = [r['id'] for r in tracker['requirements'] if r['status'] != 'accepted' or not r['evidence'] or r['outstanding']]
    if '- [ ]' in (ROOT / 'SHIP-CHECKLIST.md').read_text():
        blocked.append('SHIP-CHECKLIST')
    if blocked:
        sys.exit('Release blocked: ' + ', '.join(blocked))
print('71 acceptance records validated; matrix consistent.')
